-- Idempotent development/staging seed. Existing CMS edits are never overwritten.

insert into public.product_suites (name, slug, description, sort_order, is_published) values
  ('Office Suite','office-suite','Tools for church administration, records, finance, communication, and reporting.',10,true),
  ('Member Suite','member-suite','A secure self-service experience for members and families.',20,true)
on conflict (slug) do nothing;

insert into public.content_pages (slug,title,excerpt,blocks,status,published_at,seo) values
  ('home','Church administration, thoughtfully connected','Bring church administration, clergy support and member connection into one thoughtful digital platform.','[]'::jsonb,'published','2026-08-14T00:00:00Z','{"title":"Church administration, thoughtfully connected","description":"Bring church administration, clergy support and member connection into one thoughtful digital platform.","canonicalUrl":"/"}'::jsonb),
  ('about','About Church Govern','Why Church Govern is being built and the principles guiding the platform.','[]'::jsonb,'published','2026-08-14T00:00:00Z','{"title":"About Church Govern","description":"Why Church Govern is being built and the principles guiding the platform.","canonicalUrl":"/about"}'::jsonb),
  ('product','Church Govern product suites','Explore the Church Govern office and member suites.','[]'::jsonb,'published','2026-08-14T00:00:00Z','{"title":"Church Govern product suites","description":"Explore the Church Govern office and member suites.","canonicalUrl":"/product"}'::jsonb),
  ('security-compliance','Security & compliance','The security, privacy and governance principles intended for Church Govern.','[]'::jsonb,'published','2026-08-14T00:00:00Z','{"title":"Security & compliance","description":"The security, privacy and governance principles intended for Church Govern.","canonicalUrl":"/security-compliance"}'::jsonb),
  ('blogs','Church administration insights','Practical thinking about church administration, records, privacy and technology.','[]'::jsonb,'published','2026-08-14T00:00:00Z','{"title":"Church administration insights","description":"Practical thinking about church administration, records, privacy and technology.","canonicalUrl":"/blogs"}'::jsonb),
  ('faq','Frequently asked questions','Answers about Church Govern, digitization, implementation, security and support.','[]'::jsonb,'published','2026-08-14T00:00:00Z','{"title":"Frequently asked questions","description":"Answers about Church Govern, digitization, implementation, security and support.","canonicalUrl":"/faq"}'::jsonb),
  ('contact','Contact Church Govern','Request a demonstration, digitization assessment or general conversation.','[]'::jsonb,'published','2026-08-14T00:00:00Z','{"title":"Contact Church Govern","description":"Request a demonstration, digitization assessment or general conversation.","canonicalUrl":"/contact"}'::jsonb)
on conflict (slug) do nothing;

insert into public.product_modules (suite_id,name,slug,eyebrow,short_description,overview,benefits,features,workflow,related_slugs,sort_order,status,published_at,seo)
select suite.id, seeded.name, seeded.slug, seeded.eyebrow, seeded.summary, seeded.overview, seeded.benefits, seeded.features, seeded.workflow, seeded.related_slugs, seeded.sort_order, 'published'::public.publish_status, '2026-08-14T00:00:00Z'::timestamptz, seeded.seo
from (values
  ('office-suite','Church Dashboard','church-dashboard','A clear view of church life','Bring the day’s priorities, activity and ministry signals into one calm workspace.','The Church Dashboard gives authorized teams a shared starting point for daily administration. The final widgets and measures will be configured with each church during implementation.','["See important activity at a glance","Reduce time spent moving between records","Help leaders act on timely information"]'::jsonb,'["Role-aware overview","Upcoming activity","Pending request indicators","Configurable quick actions"]'::jsonb,'["Sign in securely","Review the church overview","Open an item that needs attention","Complete the task in its source module"]'::jsonb,array['family-management','reports','communication']::text[],1,'{"title":"Church Dashboard","description":"Bring the day’s priorities, activity and ministry signals into one calm workspace.","canonicalUrl":"/product/church-dashboard"}'::jsonb),
  ('office-suite','Family Management','family-management','One connected family record','Organize household relationships, member details and pastoral context with care.','Family Management is designed to replace disconnected registers with searchable, permission-controlled family and member records.','["Keep family relationships connected","Find records without searching paper files","Support more informed pastoral care"]'::jsonb,'["Household profiles","Member relationships","Contact details","Record history"]'::jsonb,'["Create or locate a family","Add or update members","Record relevant details","Use the record across authorized workflows"]'::jsonb,array['record-management','communication','church-directory']::text[],2,'{"title":"Family Management","description":"Organize household relationships, member details and pastoral context with care.","canonicalUrl":"/product/family-management"}'::jsonb),
  ('office-suite','Church Administration','church-administration','Daily work, brought together','Coordinate routine office activity through consistent, trackable processes.','Church Administration provides a structured place for recurring administrative work. Exact processes remain configurable to the church’s governance model.','["Standardize recurring tasks","Give teams clearer ownership","Reduce duplicated administrative effort"]'::jsonb,'["Operational task views","Structured church records","Permission-based access","Activity history"]'::jsonb,'["Choose an administrative process","Enter or review the required information","Assign or complete the work","Retain a searchable history"]'::jsonb,array['record-management','request-certificate-processing','asset-management']::text[],3,'{"title":"Church Administration","description":"Coordinate routine office activity through consistent, trackable processes.","canonicalUrl":"/product/church-administration"}'::jsonb),
  ('office-suite','Record Management','record-management','Preserve every important record','Keep essential church information organized, searchable and protected.','Record Management centralizes records while helping authorized staff maintain consistent information. Retention rules and record types are defined during implementation.','["Reduce dependence on physical registers","Improve retrieval and continuity","Protect access to sensitive information"]'::jsonb,'["Structured record categories","Search and filtering","Access controls","Change history"]'::jsonb,'["Choose a record category","Create or digitize the record","Validate key details","Retrieve it through secure search"]'::jsonb,array['family-management','request-certificate-processing','reports']::text[],4,'{"title":"Record Management","description":"Keep essential church information organized, searchable and protected.","canonicalUrl":"/product/record-management"}'::jsonb),
  ('office-suite','Request & Certificate Processing','request-certificate-processing','From request to completion','Guide service and certificate requests through a visible, consistent workflow.','This module helps church offices receive, review and complete member requests without losing context across calls, paper notes and inboxes.','["Make request status easier to follow","Reduce repeated data entry","Create a consistent member experience"]'::jsonb,'["Request intake","Status tracking","Document preparation workflow","Completion history"]'::jsonb,'["Receive a member request","Verify the supporting record","Prepare and review the output","Mark complete and notify the requester"]'::jsonb,array['request-submission','record-management','notifications']::text[],5,'{"title":"Request & Certificate Processing","description":"Guide service and certificate requests through a visible, consistent workflow.","canonicalUrl":"/product/request-certificate-processing"}'::jsonb),
  ('office-suite','Finance Management','finance-management','Clearer stewardship workflows','Support accurate financial administration, donations and reporting.','Finance Management is intended to organize authorized church finance workflows. Financial controls, local accounting requirements and integrations require discovery before deployment.','["Improve visibility for authorized leaders","Create more consistent records","Reduce manual reporting effort"]'::jsonb,'["Income and expense records","Donation tracking","Permission controls","Financial summaries"]'::jsonb,'["Record an authorized transaction","Classify it consistently","Review supporting information","Use summaries for reporting"]'::jsonb,array['reports','subscription-history','church-dashboard']::text[],6,'{"title":"Finance Management","description":"Support accurate financial administration, donations and reporting.","canonicalUrl":"/product/finance-management"}'::jsonb),
  ('office-suite','Communication','communication','Reach the right people','Coordinate timely church communication from trusted member information.','Communication helps authorized teams prepare targeted updates using the church’s current records. Delivery channels and consent rules will depend on implementation.','["Keep updates consistent","Use relevant audience groups","Reduce disconnected contact lists"]'::jsonb,'["Audience groups","Message preparation","Announcement history","Consent-aware contact data"]'::jsonb,'["Choose an audience","Prepare the message","Review and send through an enabled channel","Retain a communication record"]'::jsonb,array['notifications','family-management','church-directory']::text[],7,'{"title":"Communication","description":"Coordinate timely church communication from trusted member information.","canonicalUrl":"/product/communication"}'::jsonb),
  ('office-suite','Asset Management','asset-management','Care for shared resources','Maintain a dependable register of church property and equipment.','Asset Management creates a structured inventory for church resources, ownership context and relevant maintenance information.','["Know what the church is responsible for","Keep asset details in one place","Support maintenance planning"]'::jsonb,'["Asset register","Categories and locations","Ownership details","Maintenance notes"]'::jsonb,'["Add an asset","Assign its category and location","Maintain relevant details","Review the register when planning"]'::jsonb,array['church-administration','reports','church-dashboard']::text[],8,'{"title":"Asset Management","description":"Maintain a dependable register of church property and equipment.","canonicalUrl":"/product/asset-management"}'::jsonb),
  ('office-suite','Cemetery Management','cemetery-management','Respectful, durable records','Organize cemetery information and preserve records for future generations.','Cemetery Management supports structured burial and plot records with controlled access. Field definitions and mapping needs must be confirmed with each church.','["Preserve historically important information","Make records easier to locate","Support consistent cemetery administration"]'::jsonb,'["Burial records","Plot references","Searchable details","Supporting notes"]'::jsonb,'["Locate or create a plot reference","Add the relevant record","Review details for accuracy","Retrieve it through authorized search"]'::jsonb,array['record-management','family-management','reports']::text[],9,'{"title":"Cemetery Management","description":"Organize cemetery information and preserve records for future generations.","canonicalUrl":"/product/cemetery-management"}'::jsonb),
  ('office-suite','Reports','reports','Turn records into understanding','Give authorized leaders useful summaries without rebuilding spreadsheets.','Reports brings together information captured across enabled modules. Available reports and export formats will be confirmed during implementation.','["Reduce repetitive reporting work","Support informed decisions","Use consistent source information"]'::jsonb,'["Module-based summaries","Filters","Authorized exports","Reusable report views"]'::jsonb,'["Choose a report","Apply the relevant filters","Review the result","Export only when authorized"]'::jsonb,array['church-dashboard','finance-management','record-management']::text[],10,'{"title":"Reports","description":"Give authorized leaders useful summaries without rebuilding spreadsheets.","canonicalUrl":"/product/reports"}'::jsonb),
  ('member-suite','Member Dashboard','member-dashboard','A simple personal starting point','Help members find updates, requests and profile information in one place.','The Member Dashboard is a secure self-service home for the member-facing capabilities enabled by a church.','["Find relevant services quickly","Stay connected to church activity","Reduce routine office enquiries"]'::jsonb,'["Personal overview","Church updates","Request status","Quick links"]'::jsonb,'["Sign in securely","Review the personal overview","Choose an available service","Follow the guided next step"]'::jsonb,array['notifications','request-submission','family-profile']::text[],11,'{"title":"Member Dashboard","description":"Help members find updates, requests and profile information in one place.","canonicalUrl":"/product/member-dashboard"}'::jsonb),
  ('member-suite','Family Profile','family-profile','Keep family information current','Give members a guided view of approved household details.','Family Profile allows members to view and, where enabled, request updates to information connected to their household.','["Improve record accuracy","Make relevant details easier to access","Create a clear update process"]'::jsonb,'["Household overview","Member details","Contact information","Update requests"]'::jsonb,'["Open the family profile","Review visible information","Submit an allowed update","Church staff reviews the change when required"]'::jsonb,array['profile-management','family-management','member-dashboard']::text[],12,'{"title":"Family Profile","description":"Give members a guided view of approved household details.","canonicalUrl":"/product/family-profile"}'::jsonb),
  ('member-suite','Request Submission','request-submission','Church services without uncertainty','Let members submit eligible requests and follow their progress online.','Request Submission creates a guided entry point for church services configured by the church office.','["Reduce avoidable office visits","Capture required details consistently","Give members clearer progress visibility"]'::jsonb,'["Service catalogue","Guided request forms","Supporting information","Status view"]'::jsonb,'["Choose an available service","Provide the requested information","Submit for church review","Follow the status to completion"]'::jsonb,array['request-certificate-processing','notifications','member-dashboard']::text[],13,'{"title":"Request Submission","description":"Let members submit eligible requests and follow their progress online.","canonicalUrl":"/product/request-submission"}'::jsonb),
  ('member-suite','Subscription History','subscription-history','A clear personal history','Help members review the subscription records made available by their church.','Subscription History presents member-visible subscription information in a consistent format. The exact definition of subscriptions requires product confirmation.','["Give members convenient reference","Reduce simple record enquiries","Keep a consistent personal view"]'::jsonb,'["History view","Period filters","Record details","Member-only access"]'::jsonb,'["Open subscription history","Choose a period","Review available records","Contact the church if correction is needed"]'::jsonb,array['finance-management','member-dashboard','notifications']::text[],14,'{"title":"Subscription History","description":"Help members review the subscription records made available by their church.","canonicalUrl":"/product/subscription-history"}'::jsonb),
  ('member-suite','Notifications','notifications','Timely updates, less noise','Keep members informed about requests, events and church communication.','Notifications brings member-relevant updates into one view. Supported delivery channels and preferences will depend on deployment.','["Make important updates easier to notice","Keep request communication connected","Support timely engagement"]'::jsonb,'["In-app updates","Read status","Request notifications","Preference-ready architecture"]'::jsonb,'["Receive a relevant update","Open it for context","Take action when requested","Retain it for later reference"]'::jsonb,array['communication','request-submission','member-dashboard']::text[],15,'{"title":"Notifications","description":"Keep members informed about requests, events and church communication.","canonicalUrl":"/product/notifications"}'::jsonb),
  ('member-suite','Church Directory','church-directory','Find approved connections','Offer a privacy-aware directory based on church permissions and member choices.','Church Directory can help members find approved people or groups while respecting visibility rules. Consent and field visibility must be configured before launch.','["Support community connection","Keep directory information current","Respect member visibility choices"]'::jsonb,'["Permission-aware listings","Search","Member-approved details","Configurable visibility"]'::jsonb,'["Open the directory","Search an approved listing","View permitted information","Use the church’s enabled contact path"]'::jsonb,array['family-management','profile-management','communication']::text[],16,'{"title":"Church Directory","description":"Offer a privacy-aware directory based on church permissions and member choices.","canonicalUrl":"/product/church-directory"}'::jsonb),
  ('member-suite','Profile Management','profile-management','Personal details, responsibly managed','Help members maintain permitted profile and preference information.','Profile Management gives members control over the information and preferences their church has chosen to make self-service.','["Improve information accuracy","Make privacy choices clearer","Reduce routine change requests"]'::jsonb,'["Personal details","Contact preferences","Visibility controls","Secure account settings"]'::jsonb,'["Open profile settings","Review editable details","Save or request a change","Confirm the updated information"]'::jsonb,array['family-profile','church-directory','notifications']::text[],17,'{"title":"Profile Management","description":"Help members maintain permitted profile and preference information.","canonicalUrl":"/product/profile-management"}'::jsonb)
) as seeded(suite_slug,name,slug,eyebrow,summary,overview,benefits,features,workflow,related_slugs,sort_order,seo)
join public.product_suites suite on suite.slug=seeded.suite_slug
on conflict (slug) do nothing;

insert into public.related_modules (module_id,related_module_id,sort_order)
select source.id,target.id,relation.sort_order from (values
  ('church-dashboard','family-management',1),
  ('church-dashboard','reports',2),
  ('church-dashboard','communication',3),
  ('family-management','record-management',1),
  ('family-management','communication',2),
  ('family-management','church-directory',3),
  ('church-administration','record-management',1),
  ('church-administration','request-certificate-processing',2),
  ('church-administration','asset-management',3),
  ('record-management','family-management',1),
  ('record-management','request-certificate-processing',2),
  ('record-management','reports',3),
  ('request-certificate-processing','request-submission',1),
  ('request-certificate-processing','record-management',2),
  ('request-certificate-processing','notifications',3),
  ('finance-management','reports',1),
  ('finance-management','subscription-history',2),
  ('finance-management','church-dashboard',3),
  ('communication','notifications',1),
  ('communication','family-management',2),
  ('communication','church-directory',3),
  ('asset-management','church-administration',1),
  ('asset-management','reports',2),
  ('asset-management','church-dashboard',3),
  ('cemetery-management','record-management',1),
  ('cemetery-management','family-management',2),
  ('cemetery-management','reports',3),
  ('reports','church-dashboard',1),
  ('reports','finance-management',2),
  ('reports','record-management',3),
  ('member-dashboard','notifications',1),
  ('member-dashboard','request-submission',2),
  ('member-dashboard','family-profile',3),
  ('family-profile','profile-management',1),
  ('family-profile','family-management',2),
  ('family-profile','member-dashboard',3),
  ('request-submission','request-certificate-processing',1),
  ('request-submission','notifications',2),
  ('request-submission','member-dashboard',3),
  ('subscription-history','finance-management',1),
  ('subscription-history','member-dashboard',2),
  ('subscription-history','notifications',3),
  ('notifications','communication',1),
  ('notifications','request-submission',2),
  ('notifications','member-dashboard',3),
  ('church-directory','family-management',1),
  ('church-directory','profile-management',2),
  ('church-directory','communication',3),
  ('profile-management','family-profile',1),
  ('profile-management','church-directory',2),
  ('profile-management','notifications',3)
) relation(source_slug,target_slug,sort_order) join public.product_modules source on source.slug=relation.source_slug join public.product_modules target on target.slug=relation.target_slug
on conflict (module_id,related_module_id) do nothing;

insert into public.blog_categories(name,slug) values
  ('Digital transformation','digital-transformation'),
  ('Church administration','church-administration'),
  ('Governance','governance'),
  ('Record management','record-management'),
  ('Church finance','church-finance'),
  ('Church technology','church-technology')
on conflict (slug) do nothing;

insert into public.blog_posts(category_id,slug,title,excerpt,content,author_name,read_time_minutes,keywords,status,featured,published_at,seo)
select category.id,seeded.slug,seeded.title,seeded.excerpt,seeded.content,seeded.author_name,seeded.read_time_minutes,'{}'::text[],'published'::public.publish_status,seeded.featured,seeded.published_at,seeded.seo from (values
  ('digital-transformation','building-a-responsible-digitization-plan','Building a responsible digitization plan for church records','A practical starting point for deciding what to digitize, how to prioritize, and where safeguards belong.','[{"heading":"Begin with purpose","paragraphs":["Digitization is most useful when it answers a clear operational or pastoral need. Start by identifying the records people struggle to locate, the processes that create repeated work, and the information that is most vulnerable to loss."]},{"heading":"Prioritize with care","paragraphs":["A simple inventory can group records by condition, frequency of use, sensitivity and long-term value. This helps a church plan manageable phases instead of attempting a risky one-time migration."]},{"heading":"Protect context as well as documents","paragraphs":["Scanning a page is only one part of preservation. Consistent names, dates, categories, permissions and review steps make the resulting information dependable and easier to find."]}]'::jsonb,'Church Govern editorial team',6,true,'2026-07-28T00:00:00Z'::timestamptz,'{"title":"Building a responsible digitization plan for church records","description":"A practical starting point for deciding what to digitize, how to prioritize, and where safeguards belong.","canonicalUrl":"/blogs/building-a-responsible-digitization-plan"}'::jsonb),
  ('church-administration','less-administration-more-ministry','Less administration, more time for ministry','Where connected workflows can reduce repetitive work for clergy and church office teams.','[{"heading":"Look for repeated handoffs","paragraphs":["Administrative friction often hides in small handoffs: a request copied from a message into a register, a member asked for details the church already holds, or a report rebuilt from several files."]},{"heading":"Create one dependable path","paragraphs":["A connected workflow gives each request a clear entry point, owner and status. The goal is not to remove human care, but to protect more time for it."]},{"heading":"Measure what improves","paragraphs":["Track fewer missing details, shorter response time and reduced duplicate entry. These practical signals are often more useful than counting how many features have been enabled."]}]'::jsonb,'Church Govern editorial team',5,true,'2026-07-12T00:00:00Z'::timestamptz,'{"title":"Less administration, more time for ministry","description":"Where connected workflows can reduce repetitive work for clergy and church office teams.","canonicalUrl":"/blogs/less-administration-more-ministry"}'::jsonb),
  ('governance','privacy-by-design-for-church-data','Privacy by design for sensitive church information','Seven questions to ask before introducing a new digital process or member service.','[{"heading":"Collect with a reason","paragraphs":["Teams should be able to explain why each field is needed, who can see it, how long it is kept and how a person can ask for a correction."]},{"heading":"Make access deliberate","paragraphs":["Role-based access works best when permissions reflect real responsibilities and are reviewed when responsibilities change."]},{"heading":"Plan for the full lifecycle","paragraphs":["Privacy considerations continue after collection. Storage, exports, backups, corrections, deletion requests and incident response all need accountable processes."]}]'::jsonb,'Church Govern editorial team',7,true,'2026-06-24T00:00:00Z'::timestamptz,'{"title":"Privacy by design for sensitive church information","description":"Seven questions to ask before introducing a new digital process or member service.","canonicalUrl":"/blogs/privacy-by-design-for-church-data"}'::jsonb),
  ('record-management','a-healthier-member-record','What makes a healthier member record?','A simple framework for accurate, useful and respectfully maintained member information.','[{"heading":"Useful, not excessive","paragraphs":["A healthy record contains information that supports a defined church purpose. More fields do not automatically create better understanding."]},{"heading":"Current and accountable","paragraphs":["Give members and authorized staff clear ways to identify outdated information and request corrections, with review where the information is sensitive."]},{"heading":"Connected to action","paragraphs":["Well-maintained records reduce repeated questions, improve communication and support pastoral follow-up without replacing personal judgment."]}]'::jsonb,'Church Govern editorial team',4,false,'2026-06-02T00:00:00Z'::timestamptz,'{"title":"What makes a healthier member record?","description":"A simple framework for accurate, useful and respectfully maintained member information.","canonicalUrl":"/blogs/a-healthier-member-record"}'::jsonb),
  ('church-finance','clearer-church-finance-workflows','Designing clearer church finance workflows','How consistency, permissions and review points can strengthen everyday stewardship.','[{"heading":"Define the path","paragraphs":["Clear finance workflows specify who records, who reviews and what supporting information is required for each type of transaction."]},{"heading":"Separate responsibilities","paragraphs":["Permission design should reflect the church’s governance and review model. No software feature replaces appropriate oversight."]},{"heading":"Report from consistent records","paragraphs":["When records use shared categories and review steps, periodic summaries become easier to prepare and explain."]}]'::jsonb,'Church Govern editorial team',6,true,'2026-05-19T00:00:00Z'::timestamptz,'{"title":"Designing clearer church finance workflows","description":"How consistency, permissions and review points can strengthen everyday stewardship.","canonicalUrl":"/blogs/clearer-church-finance-workflows"}'::jsonb),
  ('church-technology','choosing-technology-that-serves-community','Choosing technology that serves community','A church-focused checklist for evaluating usability, continuity, privacy and support.','[{"heading":"Start with people","paragraphs":["Consider the confidence, devices and working conditions of the people who will use the system. A technically complete tool can still fail if everyday tasks are difficult to understand."]},{"heading":"Ask about continuity","paragraphs":["Clarify data ownership, exports, backups, support, onboarding and what happens when responsibilities change."]},{"heading":"Evaluate with real work","paragraphs":["A useful demonstration should follow common church tasks with representative information and enough time for the people responsible to ask questions."]}]'::jsonb,'Church Govern editorial team',5,false,'2026-04-30T00:00:00Z'::timestamptz,'{"title":"Choosing technology that serves community","description":"A church-focused checklist for evaluating usability, continuity, privacy and support.","canonicalUrl":"/blogs/choosing-technology-that-serves-community"}'::jsonb)
) seeded(category_slug,slug,title,excerpt,content,author_name,read_time_minutes,featured,published_at,seo) join public.blog_categories category on category.slug=seeded.category_slug
on conflict (slug) do nothing;

insert into public.faqs(category,question,answer,sort_order,is_published) values
  ('Product','What is Church Govern?','Church Govern is a church administration and member-engagement platform intended to bring records, everyday workflows and communication into one secure digital environment.',1,true),
  ('Product','Is it suitable for every denomination?','The product is being designed as denomination-neutral. A church’s structure, terminology and enabled workflows would be confirmed during discovery and implementation.',2,true),
  ('Pricing','How much does Church Govern cost?','Pricing has not yet been published. It will depend on the implementation scope, enabled modules and service requirements. Request a consultation for a documented proposal.',3,true),
  ('Security','Who can access church information?','Access is intended to be role-based so people see only what their responsibilities require. Final permission roles and governance rules must be configured with each church.',4,true),
  ('Security','Is Church Govern DPDP and GDPR compliant?','The platform is designed to support privacy-conscious implementation, but compliance depends on configuration, contracts and the church’s own processes. Formal legal and compliance documentation will be provided before production onboarding.',5,true),
  ('Digitization','Can you help digitize old registers?','Church Govern is planning a digitization enquiry service for historical and current records. Record condition, volume, page size, location and handling requirements must be assessed before a proposal is confirmed.',6,true),
  ('Deployment','Where is the platform hosted?','The final hosting architecture and data-region options are awaiting approved product documentation. These details should be confirmed as part of a security and deployment review.',7,true),
  ('Support','What support is available?','The support model, service hours and response targets will be documented in the implementation proposal. This website does not yet make an unsupported service-level claim.',8,true),
  ('Implementation','How does implementation begin?','Implementation begins with discovery: church structure, records, roles, workflows, integrations, migration needs and success criteria. A phased plan can then be agreed before configuration starts.',9,true),
  ('Implementation','Can we begin with only a few modules?','A phased rollout is expected to be possible, subject to final product and commercial confirmation. The discovery process identifies useful starting workflows and dependencies.',10,true)
on conflict (question) do nothing;

insert into public.navigation_items(label,href,location,sort_order,is_external,is_published) values
  ('About','/about','header',10,false,true),
  ('Product','/product','header',20,false,true),
  ('Trust','/security-compliance','header',30,false,true),
  ('Insights','/blogs','header',40,false,true),
  ('FAQ','/faq','header',50,false,true),
  ('Contact','/contact','header',60,false,true)
on conflict (location,href) do nothing;

insert into public.navigation_items(label,href,location,sort_order,is_external,is_published) values
  ('Privacy','/privacy','footer',10,false,true),
  ('Terms','/terms','footer',20,false,true),
  ('Accessibility','/accessibility','footer',30,false,true)
on conflict (location,href) do nothing;

insert into public.site_settings(key,value,description,is_public) values
  ('site.name','"Church Govern"'::jsonb,'Public product name',true),
  ('site.testimonials_notice','"Approved customer testimonials will appear after consent and verified attribution."'::jsonb,'Truthful fallback when no testimonials are published',true)
on conflict (key) do nothing;

