import {
  Archive,
  Bell,
  BookOpen,
  Building2,
  CalendarDays,
  ChartNoAxesCombined,
  CheckCircle2,
  Church,
  CircleUserRound,
  FileCheck2,
  FileText,
  HeartHandshake,
  Landmark,
  LayoutDashboard,
  LockKeyhole,
  Mail,
  MapPinned,
  MessageCircleMore,
  Network,
  Search,
  Send,
  ShieldCheck,
  Sparkles,
  UsersRound,
  WalletCards,
  type LucideIcon,
} from "lucide-react";

const icons: Record<string, LucideIcon> = {
  archive: Archive,
  bell: Bell,
  book: BookOpen,
  building: Building2,
  calendar: CalendarDays,
  chart: ChartNoAxesCombined,
  check: CheckCircle2,
  church: Church,
  file: FileText,
  fileCheck: FileCheck2,
  handshake: HeartHandshake,
  landmark: Landmark,
  layout: LayoutDashboard,
  lock: LockKeyhole,
  mail: Mail,
  map: MapPinned,
  message: MessageCircleMore,
  network: Network,
  search: Search,
  send: Send,
  shield: ShieldCheck,
  sparkle: Sparkles,
  user: CircleUserRound,
  users: UsersRound,
  wallet: WalletCards,
};

export function SiteIcon({ name, size = 22 }: { name: string; size?: number }) {
  const Icon = icons[name] ?? Sparkles;
  return <Icon aria-hidden="true" size={size} strokeWidth={1.8} />;
}
